name: Deploy APy to Fly.io

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'apy-server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy
        working-directory: apy-server
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl auth token $FLY_API_TOKEN >/dev/null 2>&1 || true
          flyctl deploy --remote-only --build-arg BUILDKIT_INLINE_CACHE=1

